<a href="https://colab.research.google.com/github/LennyRBriones/pytorch/blob/main/creating_a_model_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch

In PyTorch, nn.Module is very important. being the class that allows you create, store and manipulate all layers and operations in the neural networks.

This is very important because with the nn.module you only need to keep focus in the model building and results, the layers will be attended by the nn.module for you



In [2]:
import torch
import torch.nn as nn
## type of model and module to use
class TextClassifier(nn.Module):
  def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim):
                    #size, dimentions, hidden layer, output layer
    super().__init__()

    self.embedding = nn.Embedding(vocab_size, embedding_dim)
    #first the embedding  from the library, our size and the dimention

    self.rnn = nn.LSTM(embedding_dim, hidden_dim, num_layers=2, batch_first=True)
    #recurrent neural network, emedding, hidden layer, num of layers, processing batcher one by one

    self.fc = nn.Linear(hidden_dim, output_dim)
    #forward conecction to lineal layer having the hidden and output

  def fordwar(self, text):
    #always forwdard class, in this case recieving text

    embedded = self.embedding(text)
    #generating embedding

    output, (hidden, cell) = self.rnn(embedded)
    #conexion between hidden and embeed

    final_hidden = hidden[-1]
    #getting the final versión of hidden layer

    return self.fc(final_hidden)



### Reviewing code Step by step



1.   Definned a class called TextClassifier taking data from nn.Module
2.   Build the layers in our model: one layer to embedding, one layer to LSTM using 2 layers and hidden_dim hidden layers for each layer, finally a lineal layer as output
3.  Using the method forward we created an embedding with inpout text using the embedding layer
4.   Then through LSTM layer using the embedding we get the final hidden layer
5.   Finally, using the final hidden layer through the lineal layer we get the output




To be able to use the model you need to instance it like this:

In [3]:
vocab_size = 1000 # its an hyperparameter, it could be even 60,000
embedding_dim = 100 # even 700
hidden_dim = 256 #as conventional use
output_dim = 2 # because it´s a classification model

model = TextClassifier(vocab_size, embedding_dim, hidden_dim, output_dim )

Now we can see the structure of our model

In [4]:
model

TextClassifier(
  (embedding): Embedding(1000, 100)
  (rnn): LSTM(100, 256, num_layers=2, batch_first=True)
  (fc): Linear(in_features=256, out_features=2, bias=True)
)

## Examples creating tensors with Pytorch

In [11]:
escalar = torch.randn(1)
vector = torch.zeros(1,10)
matrix = torch.ones(2,2)

vector

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Also we´re able to build structures without common name

In [8]:
t5 = torch.randn(5,2,3)

t5
#the dimentions could be calculated only counting the number of "["

tensor([[[ 0.0151,  1.0154,  0.0298],
         [-1.8105,  1.3184, -0.3804]],

        [[-0.1378,  0.0733,  0.8006],
         [-1.6425,  0.2455,  1.5720]],

        [[-0.7085, -0.7432,  0.1488],
         [-1.5129, -0.4161,  1.4072]],

        [[-1.3559,  0.0230, -0.2183],
         [-0.6580, -1.4729,  0.4998]],

        [[ 0.0484,  1.3773, -0.3031],
         [-0.4817,  1.3423, -0.5412]]])

Also the tensors are able to store the values that we decide

In [10]:
torch.tensor([[2,2], [3,3]])

tensor([[2, 2],
        [3, 3]])

## Debugging operations using tensors

There are 3 most common issues working with tensors, being the following reasons:

1. Shape or size.
2. The datatype
3. The device where the tensor is located

`shape` tell us how are organizated the elements inside the tensor

In [12]:
print(f"The shape of the matrix is {matrix.shape}")
print(f"The shape of f5 is {t5.shape}")

The shape of the matrix is torch.Size([2, 2])
The shape of f5 is torch.Size([5, 2, 3])


Also we can use the